// <auto-generated />
using AgenciaViagensRcd.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace AgenciaViagensRcd.Migrations
{
    [DbContext(typeof(AgenciaViagensRcdDbContext))]
    [Migration("20211220173951_AgenciaViagensRcd")]
    partial class AgenciaViagensRcd
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.12")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("AgenciaViagensRcd.Models.Cliente", b =>
                {
                    b.Property<int>("IdCliente")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Cpf")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Telefone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdCliente");

                    b.ToTable("Cliente");
                });

            modelBuilder.Entity("AgenciaViagensRcd.Models.Destino", b =>
                {
                    b.Property<int>("IdDestino")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("NomeDestino")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("PrecoUnitario")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("UrlImagem")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdDestino");

                    b.ToTable("Destino");
                });

            modelBuilder.Entity("AgenciaViagensRcd.Models.DestinoPromo", b =>
                {
                    b.Property<int>("IdDestinoPromo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("NomeDestinoPromo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Preco")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("PrecoUnitarioPromo")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("UrlImagemPromo")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdDestinoPromo");

                    b.ToTable("DestinoPromo");
                });

            modelBuilder.Entity("AgenciaViagensRcd.Models.Pedido", b =>
                {
                    b.Property<int>("IdPedido")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("ClienteIdCliente")
                        .HasColumnType("int");

                    b.Property<int>("DestinoIdDestino")
                        .HasColumnType("int");

                    b.HasKey("IdPedido");

                    b.HasIndex("ClienteIdCliente");

                    b.HasIndex("DestinoIdDestino");

                    b.ToTable("Pedido");
                });

            modelBuilder.Entity("AgenciaViagensRcd.Models.PedidoPromo", b =>
                {
                    b.Property<int>("IdPedidoPromo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("ClienteIdCliente")
                        .HasColumnType("int");

                    b.Property<int>("DestinoPromoIdDestinoPromo")
                        .HasColumnType("int");

                    b.HasKey("IdPedidoPromo");

                    b.HasIndex("ClienteIdCliente");

                    b.HasIndex("DestinoPromoIdDestinoPromo");

                    b.ToTable("PedidoPromo");
                });

            modelBuilder.Entity("AgenciaViagensRcd.Models.Suporte", b =>
                {
                    b.Property<int>("IdSuporte")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("ClienteIdCliente")
                        .HasColumnType("int");

                    b.Property<string>("Mensagem")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdSuporte");

                    b.HasIndex("ClienteIdCliente");

                    b.ToTable("Suporte");
                });

            modelBuilder.Entity("AgenciaViagensRcd.Models.Pedido", b =>
                {
                    b.HasOne("AgenciaViagensRcd.Models.Cliente", "Cliente")
                        .WithMany()
                        .HasForeignKey("ClienteIdCliente")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AgenciaViagensRcd.Models.Destino", "Destino")
                        .WithMany()
                        .HasForeignKey("DestinoIdDestino")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cliente");

                    b.Navigation("Destino");
                });

            modelBuilder.Entity("AgenciaViagensRcd.Models.PedidoPromo", b =>
                {
                    b.HasOne("AgenciaViagensRcd.Models.Cliente", "Cliente")
                        .WithMany()
                        .HasForeignKey("ClienteIdCliente")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AgenciaViagensRcd.Models.DestinoPromo", "DestinoPromo")
                        .WithMany()
                        .HasForeignKey("DestinoPromoIdDestinoPromo")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cliente");

                    b.Navigation("DestinoPromo");
                });

            modelBuilder.Entity("AgenciaViagensRcd.Models.Suporte", b =>
                {
                    b.HasOne("AgenciaViagensRcd.Models.Cliente", "Cliente")
                        .WithMany()
                        .HasForeignKey("ClienteIdCliente")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cliente");
                });
#pragma warning restore 612, 618
        }
    }
}
